//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/03_Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""d1f79b67-52c3-4ed9-ac5c-7ce65f7374f3"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""49a01960-8099-453e-b076-95e3c4c4faba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d7e01547-6e85-48d3-be1b-8b9440e84d43"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dc619689-7543-40ea-9f4d-31aa28cc1460"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dc0953c7-0df9-485c-ab15-0059bf62c06a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""84fa5048-2da2-49c6-816d-839ab21ba00d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e0201caf-4ff9-4761-97be-595dd781ab6c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerActions"",
            ""id"": ""5126be8f-3941-41d6-a75e-1aba1ed49598"",
            ""actions"": [
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""cea3df03-21e7-4c0a-9082-c0e8612e0004"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""12324a81-aba2-4ecf-8bd5-4630b6bc0169"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swing"",
                    ""type"": ""Button"",
                    ""id"": ""e21d7de9-f7bb-4f08-a662-72589ea86d11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7b28218f-f060-46f8-9d48-a55bf35c9100"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""635ce94d-f717-469a-9cac-045d33089497"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1917be2e-2e9b-415d-8829-8958584b77e8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SwingingActions"",
            ""id"": ""e1ba6984-24a5-424e-a621-e14f01e3f6f2"",
            ""actions"": [
                {
                    ""name"": ""Swing"",
                    ""type"": ""Button"",
                    ""id"": ""a93f9a56-f1d7-4569-9dd7-79fc324b2529"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AdjustRope"",
                    ""type"": ""Button"",
                    ""id"": ""67ab7b60-1cd2-4232-a43a-2d83ea17a628"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwingForward"",
                    ""type"": ""Button"",
                    ""id"": ""ce480f59-a08d-4cee-b34d-8ef842f243bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwingRight"",
                    ""type"": ""Button"",
                    ""id"": ""e14132e1-4d95-4451-8b67-a766255282b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwingLeft"",
                    ""type"": ""Button"",
                    ""id"": ""17829cd8-0ad2-44bf-b5aa-b0251c752ede"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eaaeef65-a2f4-40a7-b216-5f267af72231"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10b88757-0764-4649-b5ee-4d7b2e6041b5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AdjustRope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54e99d70-7d45-4d84-97e4-28673bcac9bc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwingForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75432f95-e8c5-475d-b1d7-f43296c1fca3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwingRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e9819d7-697e-4348-914f-f687f3357622"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwingLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GrapplingActions"",
            ""id"": ""d301c56a-95b2-4963-901b-01356418b0ae"",
            ""actions"": [
                {
                    ""name"": ""Grapple"",
                    ""type"": ""Button"",
                    ""id"": ""e3a032f6-ba24-4dcb-9171-14980a779c4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6b93fdd1-b679-4cf4-ad7f-324d8a4a5bf4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Grapple"",
            ""id"": ""63d989bc-bc69-4a6a-9510-63a1f746c9f3"",
            ""actions"": [
                {
                    ""name"": ""GrappleObject"",
                    ""type"": ""Button"",
                    ""id"": ""e6cdb835-3711-424f-b484-8c84e0480fbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e5f340e9-fa76-4cc6-a03a-125436087655"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Movement = m_PlayerMovement.FindAction("Movement", throwIfNotFound: true);
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_Sprint = m_PlayerActions.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerActions_Jump = m_PlayerActions.FindAction("Jump", throwIfNotFound: true);
        m_PlayerActions_Swing = m_PlayerActions.FindAction("Swing", throwIfNotFound: true);
        // SwingingActions
        m_SwingingActions = asset.FindActionMap("SwingingActions", throwIfNotFound: true);
        m_SwingingActions_Swing = m_SwingingActions.FindAction("Swing", throwIfNotFound: true);
        m_SwingingActions_AdjustRope = m_SwingingActions.FindAction("AdjustRope", throwIfNotFound: true);
        m_SwingingActions_SwingForward = m_SwingingActions.FindAction("SwingForward", throwIfNotFound: true);
        m_SwingingActions_SwingRight = m_SwingingActions.FindAction("SwingRight", throwIfNotFound: true);
        m_SwingingActions_SwingLeft = m_SwingingActions.FindAction("SwingLeft", throwIfNotFound: true);
        // GrapplingActions
        m_GrapplingActions = asset.FindActionMap("GrapplingActions", throwIfNotFound: true);
        m_GrapplingActions_Grapple = m_GrapplingActions.FindAction("Grapple", throwIfNotFound: true);
        // Grapple
        m_Grapple = asset.FindActionMap("Grapple", throwIfNotFound: true);
        m_Grapple_GrappleObject = m_Grapple.FindAction("GrappleObject", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private IPlayerMovementActions m_PlayerMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerMovement_Movement;
    public struct PlayerMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerMovement_Movement;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_PlayerMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private IPlayerActionsActions m_PlayerActionsActionsCallbackInterface;
    private readonly InputAction m_PlayerActions_Sprint;
    private readonly InputAction m_PlayerActions_Jump;
    private readonly InputAction m_PlayerActions_Swing;
    public struct PlayerActionsActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Sprint => m_Wrapper.m_PlayerActions_Sprint;
        public InputAction @Jump => m_Wrapper.m_PlayerActions_Jump;
        public InputAction @Swing => m_Wrapper.m_PlayerActions_Swing;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterface != null)
            {
                @Sprint.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSprint;
                @Jump.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnJump;
                @Swing.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSwing;
                @Swing.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSwing;
                @Swing.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSwing;
            }
            m_Wrapper.m_PlayerActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Swing.started += instance.OnSwing;
                @Swing.performed += instance.OnSwing;
                @Swing.canceled += instance.OnSwing;
            }
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);

    // SwingingActions
    private readonly InputActionMap m_SwingingActions;
    private ISwingingActionsActions m_SwingingActionsActionsCallbackInterface;
    private readonly InputAction m_SwingingActions_Swing;
    private readonly InputAction m_SwingingActions_AdjustRope;
    private readonly InputAction m_SwingingActions_SwingForward;
    private readonly InputAction m_SwingingActions_SwingRight;
    private readonly InputAction m_SwingingActions_SwingLeft;
    public struct SwingingActionsActions
    {
        private @PlayerControls m_Wrapper;
        public SwingingActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Swing => m_Wrapper.m_SwingingActions_Swing;
        public InputAction @AdjustRope => m_Wrapper.m_SwingingActions_AdjustRope;
        public InputAction @SwingForward => m_Wrapper.m_SwingingActions_SwingForward;
        public InputAction @SwingRight => m_Wrapper.m_SwingingActions_SwingRight;
        public InputAction @SwingLeft => m_Wrapper.m_SwingingActions_SwingLeft;
        public InputActionMap Get() { return m_Wrapper.m_SwingingActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwingingActionsActions set) { return set.Get(); }
        public void SetCallbacks(ISwingingActionsActions instance)
        {
            if (m_Wrapper.m_SwingingActionsActionsCallbackInterface != null)
            {
                @Swing.started -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwing;
                @Swing.performed -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwing;
                @Swing.canceled -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwing;
                @AdjustRope.started -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnAdjustRope;
                @AdjustRope.performed -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnAdjustRope;
                @AdjustRope.canceled -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnAdjustRope;
                @SwingForward.started -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingForward;
                @SwingForward.performed -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingForward;
                @SwingForward.canceled -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingForward;
                @SwingRight.started -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingRight;
                @SwingRight.performed -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingRight;
                @SwingRight.canceled -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingRight;
                @SwingLeft.started -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingLeft;
                @SwingLeft.performed -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingLeft;
                @SwingLeft.canceled -= m_Wrapper.m_SwingingActionsActionsCallbackInterface.OnSwingLeft;
            }
            m_Wrapper.m_SwingingActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Swing.started += instance.OnSwing;
                @Swing.performed += instance.OnSwing;
                @Swing.canceled += instance.OnSwing;
                @AdjustRope.started += instance.OnAdjustRope;
                @AdjustRope.performed += instance.OnAdjustRope;
                @AdjustRope.canceled += instance.OnAdjustRope;
                @SwingForward.started += instance.OnSwingForward;
                @SwingForward.performed += instance.OnSwingForward;
                @SwingForward.canceled += instance.OnSwingForward;
                @SwingRight.started += instance.OnSwingRight;
                @SwingRight.performed += instance.OnSwingRight;
                @SwingRight.canceled += instance.OnSwingRight;
                @SwingLeft.started += instance.OnSwingLeft;
                @SwingLeft.performed += instance.OnSwingLeft;
                @SwingLeft.canceled += instance.OnSwingLeft;
            }
        }
    }
    public SwingingActionsActions @SwingingActions => new SwingingActionsActions(this);

    // GrapplingActions
    private readonly InputActionMap m_GrapplingActions;
    private IGrapplingActionsActions m_GrapplingActionsActionsCallbackInterface;
    private readonly InputAction m_GrapplingActions_Grapple;
    public struct GrapplingActionsActions
    {
        private @PlayerControls m_Wrapper;
        public GrapplingActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grapple => m_Wrapper.m_GrapplingActions_Grapple;
        public InputActionMap Get() { return m_Wrapper.m_GrapplingActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GrapplingActionsActions set) { return set.Get(); }
        public void SetCallbacks(IGrapplingActionsActions instance)
        {
            if (m_Wrapper.m_GrapplingActionsActionsCallbackInterface != null)
            {
                @Grapple.started -= m_Wrapper.m_GrapplingActionsActionsCallbackInterface.OnGrapple;
                @Grapple.performed -= m_Wrapper.m_GrapplingActionsActionsCallbackInterface.OnGrapple;
                @Grapple.canceled -= m_Wrapper.m_GrapplingActionsActionsCallbackInterface.OnGrapple;
            }
            m_Wrapper.m_GrapplingActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Grapple.started += instance.OnGrapple;
                @Grapple.performed += instance.OnGrapple;
                @Grapple.canceled += instance.OnGrapple;
            }
        }
    }
    public GrapplingActionsActions @GrapplingActions => new GrapplingActionsActions(this);

    // Grapple
    private readonly InputActionMap m_Grapple;
    private IGrappleActions m_GrappleActionsCallbackInterface;
    private readonly InputAction m_Grapple_GrappleObject;
    public struct GrappleActions
    {
        private @PlayerControls m_Wrapper;
        public GrappleActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GrappleObject => m_Wrapper.m_Grapple_GrappleObject;
        public InputActionMap Get() { return m_Wrapper.m_Grapple; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GrappleActions set) { return set.Get(); }
        public void SetCallbacks(IGrappleActions instance)
        {
            if (m_Wrapper.m_GrappleActionsCallbackInterface != null)
            {
                @GrappleObject.started -= m_Wrapper.m_GrappleActionsCallbackInterface.OnGrappleObject;
                @GrappleObject.performed -= m_Wrapper.m_GrappleActionsCallbackInterface.OnGrappleObject;
                @GrappleObject.canceled -= m_Wrapper.m_GrappleActionsCallbackInterface.OnGrappleObject;
            }
            m_Wrapper.m_GrappleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GrappleObject.started += instance.OnGrappleObject;
                @GrappleObject.performed += instance.OnGrappleObject;
                @GrappleObject.canceled += instance.OnGrappleObject;
            }
        }
    }
    public GrappleActions @Grapple => new GrappleActions(this);
    public interface IPlayerMovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface IPlayerActionsActions
    {
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSwing(InputAction.CallbackContext context);
    }
    public interface ISwingingActionsActions
    {
        void OnSwing(InputAction.CallbackContext context);
        void OnAdjustRope(InputAction.CallbackContext context);
        void OnSwingForward(InputAction.CallbackContext context);
        void OnSwingRight(InputAction.CallbackContext context);
        void OnSwingLeft(InputAction.CallbackContext context);
    }
    public interface IGrapplingActionsActions
    {
        void OnGrapple(InputAction.CallbackContext context);
    }
    public interface IGrappleActions
    {
        void OnGrappleObject(InputAction.CallbackContext context);
    }
}
